name: Dev CI/CD

on:
  push:
    branches: [development]

jobs:
  deploy-dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Containers
        run: docker compose up --build
